name: aqari

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/gen/images/
    - assets/gen/icons/
    - assets/gen/illustrations/
    - assets/gen/lottie/

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
