name: aqari

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  auto_size_text: ^3.0.0
  buttons_tabbar: ^1.3.10
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  easy_stepper: ^0.8.5
  equatable: ^2.0.5
  file_picker: ^8.0.5
  firebase_analytics: ^11.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_libphonenumber: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  hive_flutter: ^1.1.0
  http: ^1.2.1
  image_picker: ^1.1.2
  injectable: ^2.4.2
  intl: 0.19.0
  load_switch: ^2.1.0
  lottie: ^3.1.2
  persistent_bottom_nav_bar: ^5.0.2
  shimmer: ^3.0.0
  sizer: ^2.0.15
  step_progress_indicator: ^1.0.2
  supabase_flutter: ^2.5.3
  syncfusion_flutter_sliders: ^26.1.39
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/gen/images/
    - assets/gen/icons/
    - assets/gen/lottie/
    - assets/
    - assets/gen/
    - assets/fonts/
    - assets/fonts/Montserrat/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/gen/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
